services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8443"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:123456@mongodb:27017/mydatabase?authSource=admin
      JWT_SECRET: ${JWT_SECRET}      
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: